services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_stage_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 5

  web:
    build: .
    command: >
      sh -c "./entrypoint.sh"
    volumes:
      - static_stage:/app/staticfiles
    env_file:
      - .env.stage
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  nginx:
    image: nginx:stable-alpine
    restart: always
    ports:
      - "82:82"
    volumes:
      - ./nginx/nginx.stage.conf:/etc/nginx/conf.d/default.conf
      - static_stage:/app/staticfiles
    depends_on:
      - web

volumes:
  postgres_stage_data:
  static_stage:
