# Generated by Django 5.2.13 on 2026-04-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_image_product_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.ManyToManyField(blank=True, help_text='Select ingredients used in this product', related_name='used_in_products', to='inventory.rawproduct'),
        ),
    ]
