# Generated by Django 5.2.13 on 2026-04-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_purchase_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawproduct',
            name='average_cost',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Weighted average cost across all purchases', max_digits=10),
        ),
        migrations.AlterField(
            model_name='rawproduct',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Cost from most recent purchase', max_digits=10, verbose_name='Last Cost'),
        ),
    ]
