# Generated by Django 5.2.13 on 2026-04-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_rawproduct_cost_6decimals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=6, max_digits=16),
        ),
        migrations.AlterField(
            model_name='order',
            name='unit_price',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Price per unit', max_digits=16),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Cost to produce', max_digits=16),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=6, max_digits=16),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='item_total',
            field=models.DecimalField(decimal_places=6, default=0, editable=False, max_digits=16),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=6, help_text='Cost per unit', max_digits=16),
        ),
    ]
