# Generated by Django 5.2.13 on 2026-04-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_all_costs_6decimals'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pricing_mode',
            field=models.CharField(choices=[('margin', 'Set margin → price auto-calculated'), ('price', 'Set price  → margin auto-calculated')], default='margin', help_text='Choose what you will enter; the other value is calculated automatically.', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Cost to produce (auto from recipe)', max_digits=16),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16),
        ),
    ]
