# Generated by Django 5.2.13 on 2026-04-10 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_merge_recipe_into_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Cost to produce (auto from ingredients)', max_digits=16),
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=6, default=0, help_text='Price per unit (auto-filled from product)', max_digits=16)),
                ('delivery_cost', models.DecimalField(decimal_places=6, default=0, max_digits=16)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='inventory.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='inventory.product')),
            ],
            options={
                'verbose_name_plural': 'Quotes',
                'ordering': ['-created_at'],
            },
        ),
    ]
