# Generated by Django 5.2.13 on 2026-04-10 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_add_quote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rawproduct',
            options={'ordering': ['name', 'brand'], 'verbose_name_plural': 'Raw Products'},
        ),
        migrations.AddField(
            model_name='rawproduct',
            name='brand',
            field=models.CharField(blank=True, help_text='Brand or manufacturer', max_length=200),
        ),
        migrations.AlterField(
            model_name='rawproduct',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_products', to='inventory.provider'),
        ),
        migrations.CreateModel(
            name='ProviderCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=6, help_text='Price per unit offered by this provider', max_digits=16)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_prices', to='inventory.provider')),
                ('raw_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_prices', to='inventory.rawproduct')),
            ],
            options={
                'verbose_name': 'Provider Price',
                'verbose_name_plural': 'Provider Prices',
                'ordering': ['unit_price'],
                'unique_together': {('raw_product', 'provider')},
            },
        ),
    ]
