# Generated by Django 5.2.13 on 2026-05-30 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_alter_client_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ['name'], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='providercatalog',
            options={'ordering': ['unit_price'], 'verbose_name': 'Precio de Proveedor', 'verbose_name_plural': 'Precios de Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-purchase_date'], 'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.AlterModelOptions(
            name='purchaseitem',
            options={'verbose_name': 'Artículo de Compra', 'verbose_name_plural': 'Artículos de Compra'},
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ['-created_at'], 'verbose_name': 'Cotización', 'verbose_name_plural': 'Cotizaciones'},
        ),
        migrations.AlterModelOptions(
            name='rawproduct',
            options={'ordering': ['name', 'brand'], 'verbose_name': 'Materia Prima', 'verbose_name_plural': 'Materias Primas'},
        ),
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'verbose_name': 'Ingrediente', 'verbose_name_plural': 'Ingredientes'},
        ),
        migrations.AlterField(
            model_name='provider',
            name='address',
            field=models.TextField(blank=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='contact_person',
            field=models.CharField(blank=True, max_length=200, verbose_name='Persona de contacto'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Código postal'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='providercatalog',
            name='notes',
            field=models.CharField(blank=True, max_length=300, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='providercatalog',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_prices', to='inventory.provider', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='providercatalog',
            name='raw_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_prices', to='inventory.rawproduct', verbose_name='Materia prima'),
        ),
        migrations.AlterField(
            model_name='providercatalog',
            name='unit_price',
            field=models.DecimalField(decimal_places=6, help_text='Precio por unidad ofrecido por este proveedor', max_digits=16, verbose_name='Precio unitario'),
        ),
        migrations.AlterField(
            model_name='providercatalog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de entrega'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='inventory.provider', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de compra'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('received', 'Recibida'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='item_total',
            field=models.DecimalField(decimal_places=6, default=0, editable=False, max_digits=16, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.purchase', verbose_name='Compra'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='raw_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='inventory.rawproduct', verbose_name='Materia prima'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=6, help_text='Costo por unidad', max_digits=16, verbose_name='Costo unitario'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='inventory.client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16, verbose_name='Costo de envío'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='due_date',
            field=models.DateField(verbose_name='Fecha de vencimiento'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='inventory.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('sent', 'Enviada'), ('accepted', 'Aceptada'), ('rejected', 'Rechazada'), ('expired', 'Expirada')], default='draft', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='unit_price',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Precio por unidad (auto desde el producto)', max_digits=16, verbose_name='Precio unitario'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='rawproduct',
            name='average_cost',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Costo promedio ponderado entre todas las compras', max_digits=10, verbose_name='Costo promedio'),
        ),
        migrations.AlterField(
            model_name='rawproduct',
            name='brand',
            field=models.CharField(blank=True, help_text='Marca o fabricante', max_length=200, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='rawproduct',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Costo de la compra más reciente', max_digits=10, verbose_name='Último costo'),
        ),
        migrations.AlterField(
            model_name='rawproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='rawproduct',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='rawproduct',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='rawproduct',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_products', to='inventory.provider', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='rawproduct',
            name='quantity_in_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cantidad en stock'),
        ),
        migrations.AlterField(
            model_name='rawproduct',
            name='reorder_level',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10, verbose_name='Nivel de reorden'),
        ),
        migrations.AlterField(
            model_name='rawproduct',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogramo'), ('g', 'Gramo'), ('l', 'Litro'), ('ml', 'Mililitro'), ('unit', 'Unidad'), ('box', 'Caja'), ('dozen', 'Docena')], default='kg', max_length=20, verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='rawproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='notes',
            field=models.CharField(blank=True, help_text="Nota opcional, ej. 'tamizado', 'derretido'", max_length=200, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='inventory.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=3, help_text='Cantidad necesaria', max_digits=10, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='raw_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_uses', to='inventory.rawproduct', verbose_name='Materia prima'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(choices=[('g', 'Gramos'), ('mg', 'Miligramos'), ('pcs', 'Piezas')], default='g', max_length=5, verbose_name='Unidad'),
        ),
    ]
