# Generated by Django 5.2.13 on 2026-05-30 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_product_options_alter_provider_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplexityTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('surcharge_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Recargo %')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Nivel de Complejidad',
                'verbose_name_plural': 'Niveles de Complejidad',
                'ordering': ['surcharge_percentage'],
            },
        ),
        migrations.CreateModel(
            name='TransportZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('radius_km', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Radio (km)')),
                ('base_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tarifa base')),
                ('fee_per_km', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tarifa por km')),
            ],
            options={
                'verbose_name': 'Zona de Transporte',
                'verbose_name_plural': 'Zonas de Transporte',
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='design_notes',
            field=models.TextField(blank=True, verbose_name='Notas de diseño'),
        ),
        migrations.AddField(
            model_name='order',
            name='design_surcharge',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16, verbose_name='Recargo por diseño'),
        ),
        migrations.AddField(
            model_name='order',
            name='labor_cost',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16, verbose_name='Mano de obra'),
        ),
        migrations.AddField(
            model_name='order',
            name='persons',
            field=models.PositiveIntegerField(default=1, verbose_name='Personas'),
        ),
        migrations.AddField(
            model_name='product',
            name='base_labor_per_portion',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Mano de obra + overhead por porción (1 persona)', max_digits=10, verbose_name='Mano de obra por porción'),
        ),
        migrations.AddField(
            model_name='product',
            name='max_persons',
            field=models.PositiveIntegerField(default=100, verbose_name='Personas máximas'),
        ),
        migrations.AddField(
            model_name='product',
            name='min_persons',
            field=models.PositiveIntegerField(default=1, verbose_name='Personas mínimas'),
        ),
        migrations.AddField(
            model_name='quote',
            name='design_notes',
            field=models.TextField(blank=True, verbose_name='Notas de diseño'),
        ),
        migrations.AddField(
            model_name='quote',
            name='design_surcharge',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16, verbose_name='Recargo por diseño'),
        ),
        migrations.AddField(
            model_name='quote',
            name='labor_cost',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16, verbose_name='Mano de obra'),
        ),
        migrations.AddField(
            model_name='quote',
            name='persons',
            field=models.PositiveIntegerField(default=1, verbose_name='Personas'),
        ),
        migrations.AlterField(
            model_name='order',
            name='unit_price',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Precio por persona', max_digits=16, verbose_name='Precio por persona'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='unit_price',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Precio por persona', max_digits=16, verbose_name='Precio por persona'),
        ),
        migrations.AddField(
            model_name='product',
            name='complexity_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.complexitytier', verbose_name='Nivel de complejidad'),
        ),
    ]
