# Generated by Django 5.2.13 on 2026-07-29 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_client_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseBread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('base_labor_per_portion', models.DecimalField(decimal_places=2, default=0, help_text='Mano de obra + overhead por porción (1 persona)', max_digits=10, verbose_name='Mano de obra por porción')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Base de Pastel',
                'verbose_name_plural': 'Bases de Pastel',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Filling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('base_labor_per_portion', models.DecimalField(decimal_places=2, default=0, help_text='Mano de obra + overhead por porción (1 persona)', max_digits=10, verbose_name='Mano de obra por porción')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Relleno',
                'verbose_name_plural': 'Rellenos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('base_labor_per_portion', models.DecimalField(decimal_places=2, default=0, help_text='Mano de obra + overhead por porción (1 persona)', max_digits=10, verbose_name='Mano de obra por porción')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Cubierta',
                'verbose_name_plural': 'Cubiertas',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='base_bread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.basebread', verbose_name='Base de pastel'),
        ),
        migrations.AddField(
            model_name='product',
            name='filling',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.filling', verbose_name='Relleno'),
        ),
        migrations.AddField(
            model_name='product',
            name='topping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.topping', verbose_name='Cubierta'),
        ),
        migrations.CreateModel(
            name='BaseBreadIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Cantidad necesaria por porción (1 persona)', max_digits=10, verbose_name='Cantidad')),
                ('unit', models.CharField(choices=[('g', 'Gramos'), ('mg', 'Miligramos'), ('pcs', 'Piezas')], default='g', max_length=5, verbose_name='Unidad')),
                ('notes', models.CharField(blank=True, help_text="Nota opcional, ej. 'tamizado', 'derretido'", max_length=200, verbose_name='Notas')),
                ('base_bread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='inventory.basebread', verbose_name='Base de pastel')),
                ('raw_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_bread_uses', to='inventory.rawproduct', verbose_name='Materia prima')),
            ],
            options={
                'verbose_name': 'Ingrediente de Base',
                'verbose_name_plural': 'Ingredientes de Base',
                'unique_together': {('base_bread', 'raw_product')},
            },
        ),
        migrations.CreateModel(
            name='FillingIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Cantidad necesaria por porción (1 persona)', max_digits=10, verbose_name='Cantidad')),
                ('unit', models.CharField(choices=[('g', 'Gramos'), ('mg', 'Miligramos'), ('pcs', 'Piezas')], default='g', max_length=5, verbose_name='Unidad')),
                ('notes', models.CharField(blank=True, help_text="Nota opcional, ej. 'tamizado', 'derretido'", max_length=200, verbose_name='Notas')),
                ('filling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='inventory.filling', verbose_name='Relleno')),
                ('raw_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filling_uses', to='inventory.rawproduct', verbose_name='Materia prima')),
            ],
            options={
                'verbose_name': 'Ingrediente de Relleno',
                'verbose_name_plural': 'Ingredientes de Relleno',
                'unique_together': {('filling', 'raw_product')},
            },
        ),
        migrations.CreateModel(
            name='ToppingIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Cantidad necesaria por porción (1 persona)', max_digits=10, verbose_name='Cantidad')),
                ('unit', models.CharField(choices=[('g', 'Gramos'), ('mg', 'Miligramos'), ('pcs', 'Piezas')], default='g', max_length=5, verbose_name='Unidad')),
                ('notes', models.CharField(blank=True, help_text="Nota opcional, ej. 'tamizado', 'derretido'", max_length=200, verbose_name='Notas')),
                ('raw_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topping_uses', to='inventory.rawproduct', verbose_name='Materia prima')),
                ('topping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='inventory.topping', verbose_name='Cubierta')),
            ],
            options={
                'verbose_name': 'Ingrediente de Cubierta',
                'verbose_name_plural': 'Ingredientes de Cubierta',
                'unique_together': {('topping', 'raw_product')},
            },
        ),
    ]
