# Generated by Django 5.2.13 on 2026-07-29 19:47

from django.db import migrations
from decimal import Decimal


def convert_existing_products(apps, schema_editor):
    Product = apps.get_model('inventory', 'Product')
    BaseBread = apps.get_model('inventory', 'BaseBread')
    BaseBreadIngredient = apps.get_model('inventory', 'BaseBreadIngredient')
    Filling = apps.get_model('inventory', 'Filling')
    Topping = apps.get_model('inventory', 'Topping')
    RecipeIngredient = apps.get_model('inventory', 'RecipeIngredient')

    default_filling, _ = Filling.objects.get_or_create(
        name='Sin relleno',
        defaults={
            'description': 'Relleno predeterminado para productos existentes',
            'base_labor_per_portion': Decimal('0'),
            'is_available': True,
        },
    )
    default_topping, _ = Topping.objects.get_or_create(
        name='Sin cubierta',
        defaults={
            'description': 'Cubierta predeterminada para productos existentes',
            'base_labor_per_portion': Decimal('0'),
            'is_available': True,
        },
    )

    for product in Product.objects.filter(category='cake'):
        base_bread = BaseBread.objects.create(
            name=f'{product.name}',
            description=product.description or '',
            base_labor_per_portion=product.base_labor_per_portion or Decimal('0'),
            is_available=True,
        )

        for ri in RecipeIngredient.objects.filter(product=product):
            BaseBreadIngredient.objects.create(
                base_bread=base_bread,
                raw_product=ri.raw_product,
                quantity=ri.quantity,
                unit=ri.unit,
                notes=ri.notes or '',
            )

        product.base_bread = base_bread
        product.filling = default_filling
        product.topping = default_topping
        product.save(update_fields=['base_bread', 'filling', 'topping'])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_basebread_filling_topping_product_base_bread_and_more'),
    ]

    operations = [
        migrations.RunPython(convert_existing_products),
    ]
