# Generated by Django 5.2.13 on 2026-07-29 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_rename_rawproduct_brand_to_old_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rawproduct',
            options={'ordering': ['name', 'brand__name', 'old_brand'], 'verbose_name': 'Materia Prima', 'verbose_name_plural': 'Materias Primas'},
        ),
        migrations.AddField(
            model_name='rawproduct',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.brand', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='rawproduct',
            name='old_brand',
            field=models.CharField(blank=True, help_text='Marca o fabricante', max_length=200, verbose_name='Marca (anterior)'),
        ),
    ]
