# Generated by Django 5.2.13 on 2026-07-29 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_add_rawproduct_brand_fk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rawproduct',
            options={'ordering': ['name', 'brand__name'], 'verbose_name': 'Materia Prima', 'verbose_name_plural': 'Materias Primas'},
        ),
        migrations.RemoveField(
            model_name='rawproduct',
            name='old_brand',
        ),
    ]
