# Generated by Django 5.2.13 on 2026-07-29 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_remove_rawproduct_old_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Etiqueta de Evento',
                'verbose_name_plural': 'Etiquetas de Evento',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='color_scheme',
            field=models.CharField(blank=True, max_length=200, verbose_name='Esquema de colores'),
        ),
        migrations.AddField(
            model_name='product',
            name='design_description',
            field=models.TextField(blank=True, verbose_name='Descripción de diseño'),
        ),
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[('nino', 'Niño'), ('nina', 'Niña'), ('hombre', 'Hombre'), ('mujer', 'Mujer'), ('unisex', 'Unisex')], max_length=20, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='product',
            name='show_in_gallery',
            field=models.BooleanField(default=False, verbose_name='Mostrar en galería'),
        ),
        migrations.AddField(
            model_name='product',
            name='event_tags',
            field=models.ManyToManyField(blank=True, to='inventory.eventtag', verbose_name='Etiquetas de evento'),
        ),
    ]
