# Generated by Django 5.2.13 on 2026-07-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_add_rawproduct_brand_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawproduct',
            name='old_brand',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Marca (anterior)'),
        ),
    ]
