# Generated by Django 5.2.13 on 2026-07-29 22:16

from django.db import migrations


def set_existing_products_defaults(apps, schema_editor):
    Product = apps.get_model('inventory', 'Product')
    Product.objects.filter(is_available=True).update(show_in_gallery=True)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_eventtag_product_color_scheme_and_more'),
    ]

    operations = [
        migrations.RunPython(set_existing_products_defaults, reverse_code=migrations.RunPython.noop),
    ]
