# Generated by Django 5.2.13 on 2026-07-29 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_set_defaults_for_existing_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de entrega'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16, verbose_name='Costo de envío'),
        ),
        migrations.AddField(
            model_name='order',
            name='stock_verified',
            field=models.BooleanField(default=False, verbose_name='Stock verificado'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('in_production', 'En producción'), ('delivered', 'Entregado'), ('paid', 'Pagado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado'),
        ),
    ]
