# Generated by Django 5.2.13 on 2026-08-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_remove_basebreadingredient_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Destacado en galería'),
        ),
    ]
