# Generated by Django 5.2.13 on 2026-08-12 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_product_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='base_bread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.basebread', verbose_name='Base de pastel'),
        ),
        migrations.AddField(
            model_name='quote',
            name='benefit_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16, verbose_name='Beneficio'),
        ),
        migrations.AddField(
            model_name='quote',
            name='benefit_percentage',
            field=models.DecimalField(decimal_places=2, default=50, help_text='Porcentaje de beneficio aplicado sobre el costo', max_digits=5, verbose_name='% Beneficio'),
        ),
        migrations.AddField(
            model_name='quote',
            name='complexity_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.complexitytier', verbose_name='Nivel de complejidad'),
        ),
        migrations.AddField(
            model_name='quote',
            name='filling',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.filling', verbose_name='Relleno'),
        ),
        migrations.AddField(
            model_name='quote',
            name='ingredient_cost',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16, verbose_name='Ingredientes'),
        ),
        migrations.AddField(
            model_name='quote',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Nombre del pastel'),
        ),
        migrations.AddField(
            model_name='quote',
            name='topping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.topping', verbose_name='Cubierta'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='inventory.product', verbose_name='Producto (opcional)'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='unit_price',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Precio por persona (incluye beneficio y diseño)', max_digits=16, verbose_name='Precio por persona'),
        ),
    ]
