# Generated by Django 5.2.13 on 2026-08-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_quote_base_bread_quote_benefit_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='show_delivery_on_pdf',
            field=models.BooleanField(default=True, verbose_name='Incluir envío en el PDF'),
        ),
    ]
