# Generated by Django 5.2.13 on 2026-08-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_quote_show_delivery_on_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='show_delivery_on_pdf',
            field=models.BooleanField(default=False, verbose_name='Incluir envío en el PDF'),
        ),
    ]
