# Generated by Django 5.2.13 on 2026-08-12 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_alter_quote_show_delivery_on_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agregado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Descripción')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Agregado',
                'verbose_name_plural': 'Agregados',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='quote',
            name='extras_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=16, verbose_name='Agregados'),
        ),
        migrations.AddField(
            model_name='quote',
            name='agregados',
            field=models.ManyToManyField(blank=True, to='inventory.agregado', verbose_name='Agregados'),
        ),
    ]
