# Generated by Django 5.2.13 on 2026-08-12 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_agregado_quote_extras_amount_quote_agregados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='agregados',
        ),
        migrations.CreateModel(
            name='QuoteAgregado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Descripción')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agregados', to='inventory.quote', verbose_name='Cotización')),
            ],
            options={
                'verbose_name': 'Agregado de Cotización',
                'verbose_name_plural': 'Agregados de Cotización',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Agregado',
        ),
    ]
