# Generated by Django 5.2.13 on 2026-08-12 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_remove_quote_agregados_quoteagregado_delete_agregado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='show_delivery_on_pdf',
        ),
    ]
